version: build-{build}-{branch}

environment:
  global:
    # At the moment PyPI has no wheels of ZODB and zope.*.
    PIP_FIND_LINKS: "https://debesis.gedmin.as/wheels/"
    # At the moment PyPI has no Windows wheels for lxml, and the Zope
    # wineggbuilder only builds older lxml eggs (that I then convert to wheels)
    # for some reason.  Ask pip to use binary wheels I've available of older
    # lxml versions in preference to building the latest lxml from source.
    PIP_ONLY_BINARY: "lxml"
  matrix:
    # https://www.appveyor.com/docs/installed-software#python lists available
    # versions
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python37"

init:
  - "echo %PYTHON%"

install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python --version
  - pip install tox

build: off

test_script:
  - tox -e py
