#
# Options
#

# Or you may want to select an explicit Python version, e.g. python2.7
PYTHON = python

#
# Bit of an implementation detail: all scripts generated by buildout
#
scripts = bin/test bin/python bin/zodbbrowser

# my release rules
FILE_WITH_VERSION = src/zodbbrowser/__init__.py
FILE_WITH_CHANGELOG = CHANGES.rst


#
# Interesting targets
#

.PHONY: all
all: $(scripts)

.PHONY: test
test: bin/test
	bin/test -s zodbbrowser --auto-color -v1

.PHONY: check
check:
	tox

# test with pager
.PHONY: testp
testp: bin/test
	bin/test -s zodbbrowser -vc 2>&1 |less -RFX

.PHONY: coverage
coverage:
	tox -e coverage

.PHONY: checkzope2
checkzope2: dist python/bin/python
	version=`$(PYTHON) setup.py --version` && \
	rm -rf tmp && \
	mkdir tmp && \
	cd tmp && \
	tar xvzf ../dist/zodbbrowser-$$version.tar.gz && \
	cd zodbbrowser-$$version && \
	../../python/bin/python bootstrap.py && \
	bin/buildout -c zope2.cfg && \
	bin/test -s zodbbrowser


include release.mk


#
# Implementation
#

bin/buildout: python/bin/python bootstrap.py
	python/bin/pip install -U setuptools
	python/bin/python bootstrap.py

python/bin/python:
	virtualenv -p $(PYTHON) python

$(scripts): bin/buildout
	bin/buildout
	touch -c $(scripts)
